Jhia 38 trip header
JumpTwentyFour/wandersnap-app pull request #10
Opened 2023-08-23 14:02 UTC by Joshw8

Created the Trip Header component.

<img width="387" alt="Screenshot 2023-08-23 at 15 02 26" src="https://github.com/JumpTwentyFour/wandersnap-app/assets/43063558/4445f7a2-adac-43bf-91a2-8a9a3e26816c">

2023-08-23 14:54 UTC, danielj24 requested changes

2023-08-23 14:54 UTC, danielj24 commented on src/components/headers/TripHeader.tsx
> +const TripHeader = () => {
function declaration please :)

2023-08-23 14:54 UTC, danielj24 commented on src/components/headers/TripHeader.tsx
> +import { useNavigation } from '@react-navigation/native'
put this above the local imports please

2023-08-23 14:54 UTC, danielj24 commented on src/components/headers/TripHeader.tsx
> +import IconButton from '../pressables/IconButton'
Can we use the `@` alias always instead of relative paths?

`@/components/pressables/IconButton`

2023-08-23 14:54 UTC, danielj24 commented on src/components/headers/TripHeader.tsx
> +
Remove new line :)

2023-08-23 14:54 UTC, danielj24 commented on src/components/pressables/IconButton.tsx
> +    <Pressable onPress={(event) => onPress ? onPress(event) : null} className={cn(buttonStyles, buttonBackground)} disabled={disabled}>
You can do this like:

`onPress={onPress}`

If it's `undefined` it wont be used and any params get passed through automatically

2023-08-24 08:27 UTC, Joshw8 commented on src/components/headers/TripHeader.tsx
> +const TripHeader = () => {
👍

2023-08-24 08:27 UTC, Joshw8 commented on src/components/headers/TripHeader.tsx
> +import { useNavigation } from '@react-navigation/native'
👍

2023-08-24 08:27 UTC, Joshw8 commented on src/components/headers/TripHeader.tsx
> +
👍

2023-08-24 08:36 UTC, merged